### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xecmascript#10]
In order to launch we should have:

- [x] ECMAScript as a submodule in [x-api](https://github.com/exercism/x-api/tree/master/problems)
- [x] at least 10 problems
- [x] a "how to get started" topic in the [help repo](https://github.com/exercism/docs) repo (`app/pages/languages/getting-started-with-ecmascript.md`)
- [x] one to a handful of people willing to check exercism regularly (daily?) for nitpicks to ensure that the track gets off on the right foot
- [x] add track implementors and other designated nitpickers as mentors to the track
- [ ] toggle `"active"` to `true` in `config.json`

Some tracks have been more successful than others, and I believe the key features of the successful tracks are:

* Each submission receives feedback quickly, preferably within the first 24 hours.
* The nitpicks do not direct users to do specific things, but rather ask questions challenging people to think about different aspects of their solution, or explore new aspects of the language.

For more about contributing to language tracks on exercism, check out the Problem API Contributing guide: https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md

**Comment by rchavarria** [comment]
- [x] *LANGUAGE as a submodule in [x-api](https://github.com/exercism/x-api/tree/master/problems)*: I can find it there
- [x] *at least 10 problems*: done. I plan to bring more exercises to the track
- [x] *a "how to get started" topic in the [help repo](https://github.com/exercism/docs) repo (`app/pages/languages/getting-started-with-LANGUAGE.md`)*: it was added
- [ ] *one to a handful of people willing to check exercism regularly (daily?) for nitpicks to ensure that the track gets off on the right foot*: I'm willing to do it, but I'm not sure I can commit to do it daily. I was planning to contact some exercism users from the JavaScript track. But, nobody knows, maybe nobody replies
- [ ] *add track implementors and other designated nitpickers as mentors to the track*: I think this point depends on the point above
- [ ] *toggle `"active"` to `true` in `config.json`*: not yet, but it's getting closer

Completed points are ok for you? What do you think about not completed ones?

**Comment by kytrinyx** [comment]
I would be happiest if there are at least 3 people committed to checking in fairly regularly. From experience with other tracks, one person is not enough and it can quickly turn into a ghost town.

I'll add you as track mentor and track implementor.

**Comment by kytrinyx** [comment]
Oh, you're already listed as a track maintainer--you have commit on both this repo and the javascript one.

**Comment by matthewmorgan** [comment]
Hi Katrina and Rubén, 

I'm on board with helping mentor this track.  Ready to go when you are!

**Comment by kytrinyx** [comment]
Awesome, thank you so much, @matthewmorgan!

**Comment by marioIncandeza** [comment]
Hi,
I'm also on board. Let's do it.

**Comment by kytrinyx** [comment]
Cool, I'll add you all as mentors on the ECMAScript track.

**Comment by kytrinyx** [comment]
Done ^^

**Comment by rchavarria** [comment]
Nice! Thanks @matthewmorgan  and @marioIncandeza! 

@kytrinyx, are we ready to activate the thing in `config.json` and become public or do you think we would need to do something more?

**Comment by kytrinyx** [comment]
We're ready activate it, I think!

**Comment by matthewmorgan** [comment]
@kytrinyx @rchavarria - am I supposed to see anything new at this point?  Doesn't look like the track is active yet.  Let me know if there's something I'm meant to do.

**Comment by kytrinyx** [comment]
Once it's activated I'll post back here. At that point the thing to do is to go check the "Exercises" list for ECMAScript regularly to see if anyone needs feedback.

**Comment by matthewmorgan** [comment]
Thanks!

Matt Morgan




On Thu, Oct 8, 2015 at 12:13 PM -0700, "Katrina Owen" <notifications@github.com> wrote:












Once it's activated I'll post back here. At that point the thing to do is to go check the "Exercises" list for ECMAScript regularly to see if anyone needs feedback.

**Comment by matthewmorgan** [comment]
Hi,  Just checking this track out and the 'Leap' exercise is missing its ```package.json``` file.

Also, on 'Leap' and 'Hello World' I had to manually ```npm install --save``` for ```del``` and ```yargs```.  I don't know if this is a problem with my configuration or an issue with the exercise files.  FYI.

**Comment by rchavarria** [comment]
Yep. I found the same error while starting using the language track. There is a PR fixing it ([Fix an error that prevents users to run tests](https://github.com/exercism/xecmascript/pull/32)). I hope it will be merged soon.

**Comment by matthewmorgan** [comment]
Great.  Very excited to see this happening!

**Comment by rchavarria** [comment]
@kytrinyx Do you think this issue can be closed?

**Comment by kytrinyx** [comment]
Yepp. Thanks!
